UPDATE MAL.Review SET reviewText = 'l;kasdjfklavjasldkfjl;askdjfaiosdfklj', user_id = 1, likes = 0, dislikes = 0, anime_id = 1, grade = 69 WHERE review_id = 1;
UPDATE MAL.Review SET reviewText = 'glksjgfioeur', user_id = 2, likes = 0, dislikes = 3, anime_id = 1, grade = 15 WHERE review_id = 3;
UPDATE MAL.Review SET reviewText = 'g;ksldfjgihkwerw', user_id = 2, likes = 1, dislikes = 1, anime_id = 2, grade = 78 WHERE review_id = 4;
UPDATE MAL.Review SET reviewText = 'Melhor anime, muito melhor que FMAB', user_id = 2, likes = 999, dislikes = 0, anime_id = 8, grade = 100 WHERE review_id = 7;
UPDATE MAL.Review SET reviewText = 'Esse anime mudou minha vida', user_id = 2, likes = 80, dislikes = 0, anime_id = 8, grade = 100 WHERE review_id = 8;
UPDATE MAL.Review SET reviewText = 'Curou minha depressao', user_id = 3, likes = 894, dislikes = 0, anime_id = 8, grade = 100 WHERE review_id = 9;
UPDATE MAL.Review SET reviewText = 'Me inspirou a ser uma pessoa melhor', user_id = 4, likes = 63, dislikes = 0, anime_id = 8, grade = 100 WHERE review_id = 10;
UPDATE MAL.Review SET reviewText = 'Muito grito pouca luta', user_id = 2, likes = 12, dislikes = 15, anime_id = 21, grade = 14 WHERE review_id = 11;
UPDATE MAL.Review SET reviewText = 'wqersdaf', user_id = 6, likes = 0, dislikes = 0, anime_id = 23, grade = 90 WHERE review_id = 16;
UPDATE MAL.Review SET reviewText = 'wqersdaf', user_id = 6, likes = 0, dislikes = 0, anime_id = 23, grade = 90 WHERE review_id = 17;
UPDATE MAL.Review SET reviewText = 'wqersdaf', user_id = 6, likes = 0, dislikes = 0, anime_id = 23, grade = 90 WHERE review_id = 18;
UPDATE MAL.Review SET reviewText = 'fruycdhgtv ', user_id = 6, likes = 0, dislikes = 0, anime_id = 23, grade = 90 WHERE review_id = 19;
UPDATE MAL.Review SET reviewText = '', user_id = 6, likes = 0, dislikes = 0, anime_id = 1, grade = 90 WHERE review_id = 30;
UPDATE MAL.Review SET reviewText = 'review_text', user_id = 6, likes = 0, dislikes = 0, anime_id = 1, grade = 90 WHERE review_id = 38;
UPDATE MAL.Review SET reviewText = 'asdf', user_id = 6, likes = 0, dislikes = 0, anime_id = 1, grade = 90 WHERE review_id = 41;
UPDATE MAL.Review SET reviewText = '', user_id = 6, likes = 0, dislikes = 0, anime_id = 4, grade = 90 WHERE review_id = 42;
UPDATE MAL.Review SET reviewText = 'MY BESTO FRIENDO', user_id = 6, likes = 0, dislikes = 0, anime_id = 7, grade = 90 WHERE review_id = 43;
UPDATE MAL.Review SET reviewText = 'Uma lição sobre religiao', user_id = 6, likes = 0, dislikes = 0, anime_id = 9, grade = 90 WHERE review_id = 44;
UPDATE MAL.Review SET reviewText = 'Family friendly', user_id = 6, likes = 0, dislikes = 0, anime_id = 10, grade = 90 WHERE review_id = 45;
UPDATE MAL.Review SET reviewText = 'Perdoar', user_id = 6, likes = 0, dislikes = 0, anime_id = 11, grade = 90 WHERE review_id = 46;
UPDATE MAL.Review SET reviewText = 'Como tratar sua meia irma', user_id = 6, likes = 0, dislikes = 0, anime_id = 12, grade = 90 WHERE review_id = 47;
UPDATE MAL.Review SET reviewText = 'Ela é maior de 18', user_id = 6, likes = 0, dislikes = 0, anime_id = 13, grade = 90 WHERE review_id = 48;
UPDATE MAL.Review SET reviewText = 'Lição de aceitação', user_id = 6, likes = 0, dislikes = 0, anime_id = 14, grade = 90 WHERE review_id = 49;
UPDATE MAL.Review SET reviewText = 'Como se comportar na escola', user_id = 6, likes = 0, dislikes = 0, anime_id = 15, grade = 90 WHERE review_id = 50;
UPDATE MAL.Review SET reviewText = 'Não voe perto do Sol Ikarus', user_id = 6, likes = 0, dislikes = 0, anime_id = 16, grade = 90 WHERE review_id = 51;
UPDATE MAL.Review SET reviewText = 'klfjga', user_id = 6, likes = 0, dislikes = 0, anime_id = 17, grade = 90 WHERE review_id = 52;
UPDATE MAL.Review SET reviewText = 'asdf', user_id = 6, likes = 0, dislikes = 0, anime_id = 19, grade = 90 WHERE review_id = 53;
UPDATE MAL.Review SET reviewText = 'asdf', user_id = 6, likes = 0, dislikes = 0, anime_id = 19, grade = 90 WHERE review_id = 54;
UPDATE MAL.Review SET reviewText = 'asdf', user_id = 6, likes = 0, dislikes = 0, anime_id = 20, grade = 90 WHERE review_id = 55;
