package com.dispy.enum

enum class AnimeGenre {
    ACTION, ADVENTURE, COMEDY, DRAMA, FANTASY, HAREM, HISTORIC, IDOLS, ISEKAI, MAHO_SHOJO, MECHA, MUSIC,
    MYSTERY, POS_APOCALYPTIC, SCI_FI, SEINEM, SHOUNEN, SHOUJO, SLICE_OF_LIVE, SPORTS, SUPERNATURAL,
    THRILLER, YURI, YAOI
}